### ISSUE TITLE
Applying a table style to a reference docx 

### ISSUE THREAD

**Issue by ammaraziz** [davidgohel/officedown#130]
Hi David,

Thanks for creating and maintaining officer/officedown.

I have a word template file (`.dotx`) that I am trying to add text to using rmarkdown. My yaml header is:

```
---
output:
  officedown::rdocx_document:
    reference_docx: "Work Instruction v1.dotx"
    tables:
      style: Table
      layout: autofit
      width: 1.0
      topcaption: true
      tab.lp: 'tab:'
      caption:
        style: Table Caption
        pre: 'Table '
        sep: ': '
        tnd: 0
        tns: '-'
        fp_text: !expr officer::fp_text_lite(bold = TRUE)
      conditional:
        first_row: true
        first_column: false
        last_row: false
        last_column: false
        no_hband: false
        no_vband: true
---
```
This was copied nearly wholesale from https://davidgohel.github.io/officedown/reference/rdocx_document.html

Now the contents:

```
\```{r, echo=F, warning=F}
library(officedown)
library(officer)
\```

# &emsp;Purpose

# &emsp;Scope

# &emsp;Safety Considerations and Warnings

# &emsp;Related documents

# &emsp;References

# &emsp;Change History
\```{r, echo=FALSE}
ch = data.frame(`Version number` = c(rep("", 5)), 
                `Authorised date` = c(rep("", 5)), 
                `Summary of change` = c(rep("", 5)))
ch
\```
```

Please ignore the escape character (`\` used above). 

When I try to knit, I get this error:

```
Error in process_stylenames(x$doc_obj, x$styles) : 
  Some styles can not be found in the document: 'Table'
Calls: <Anonymous> ... <Anonymous> -> print -> print.rdocx -> process_stylenames
Execution halted
```

I've tried the following:

- Omitting the dataframe output fixes this issue.
- Edited the dotx to add a Table design this fixes the issue.
- Using template as docx (without adding Table design)

Could I be misunderstanding the `Table` options in the yaml part of the rmarkdown?

Session info:

```
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 21

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C               LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8     LC_MONETARY=en_AU.UTF-8   
 [6] LC_MESSAGES=en_AU.UTF-8    LC_PAPER=en_AU.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] zip_2.3.0               Rcpp_1.0.11             fontBitstreamVera_0.1.1 later_1.3.1             compiler_4.1.2          gfonts_0.2.0           
 [7] tools_4.1.2             digest_0.6.33           uuid_1.1-1              lifecycle_1.0.3         jsonlite_1.8.7          evaluate_0.22          
[13] memoise_2.0.1           rlang_1.1.1             shiny_1.7.5.1           cli_3.6.1               rstudioapi_0.15.0       curl_5.1.0             
[19] crul_1.4.0              yaml_2.3.7              fontLiberation_0.1.0    officedown_0.3.1        xfun_0.40               fastmap_1.1.1          
[25] officer_0.6.3           xml2_1.3.5              knitr_1.44              gdtools_0.3.4           systemfonts_1.0.5       askpass_1.2.0          
[31] glue_1.6.2              httpcode_0.3.0          R6_2.5.1                textshaping_0.3.7       rvg_0.3.3               rmarkdown_2.25         
[37] magrittr_2.0.3          fontquiver_0.2.1        ellipsis_0.3.2          promises_1.2.1          htmltools_0.5.6.1       xtable_1.8-4           
[43] mime_0.12               httpuv_1.6.12           ragg_1.2.6              openssl_2.1.1           cachem_1.0.8            crayon_1.5.2   
```
