### ISSUE TITLE
Support for multiple authors in similar manner to bookdown::pdf_document

### ISSUE THREAD

**Issue by zeigerpuppy** [davidgohel/officedown#149]
It would be great for `officedown::rdocx_document` to support multiple authors and affiliations.

An example of the formatting in a YAML header would be:

```yaml
---
title: "A Multiauthor Paper"
tags: RMarkdown, Research, Article
authors:
  - name: Author One
    affiliation: [2,3]
  - name: Author Two
    affiliation: 1
affiliations:
  - name: A University
    index: 1
  - name: Institute1
    index: 2
  - name: Institute2
    index: 3  
citation_author: Author One
date: 10 June 2025
year: 2025
bibliography: paper.bib
link-citations: yes
output:
  officedown::rdocx_document:
    tables:
      style: Table
      layout: autofit
      width: 1.0
      caption:
       style: Table Caption
       pre: 'Table '
       sep: ': '
      conditional:
       first_row: true
       first_column: false
       last_row: false
       last_column: false
       no_hband: false
       no_vband: true
  bookdown::pdf_document2:
    template: templates/template.tex
    toc: false
    number_sections: false
    global_numbering: true
    latex_engine: xelatex
    keep_tex: true
    includes:
      in_header: preamble.tex
---
```

This produces output with:

Author One<sup>2,3</sup>, Author Two<sup>1</sup>
1. University  2. Institute1  3. Institite2

Note that this formatting works with the `bookdown::pdf_document2` output.
