### ISSUE TITLE
Sections numbered twice (1.0 and 0.1)

### ISSUE THREAD

**Issue by katerinabc** [davidgohel/officedown#59]
Hi, 

I'm generating reports based on collected data using markdown. The script was developed and test in Autumn 2020. When running the code again yesterday, I experienced an issue with headings being numbered twice see screenshot: 
![Screen Shot 2021-02-05 at 22 51 26](https://user-images.githubusercontent.com/11277873/107097464-e53bee00-6804-11eb-8bbe-6a579fc8de9e.png). When creating a pdf or HTML report, the sections are only numbered once. 

My header is 

``````

---
title: "Michelle SNA Report"
#author: "Katerina Bohle Carbonell"
# output for html in report_v3.Rmd
date: "5th Feb 2021"
always_allow_html: true
output:
 bookdown::markdown_document2:
    base_format: officedown::rdocx_document
    toc: true
---
``````

and r setup is
``````
knitr::opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE, eval = TRUE, 
  fig.width = 7, #width = 8 --> figure outside word margin; width = 7 --> figure cut off
  #fig.height = 8,
  fig.align = 'center', 
  dpi = 300
  
)
``````

``````
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

loaded via a namespace (and not attached):
 [1] pillar_1.4.7      compiler_3.5.2    tools_3.5.2      
 [4] digest_0.6.27     jsonlite_1.7.2    evaluate_0.14    
 [7] lifecycle_0.2.0   tibble_3.0.4      gtable_0.3.0     
[10] viridisLite_0.3.0 pkgconfig_2.0.3   rlang_0.4.10     
[13] cli_2.2.0         rstudioapi_0.13   yaml_2.2.1       
[16] xfun_0.20         dplyr_1.0.2       httr_1.4.2       
[19] knitr_1.30        generics_0.1.0    vctrs_0.3.6      
[22] htmlwidgets_1.5.3 grid_3.5.2        tidyselect_1.1.0 
[25] glue_1.4.2        data.table_1.13.6 R6_2.5.0         
[28] fansi_0.4.1       plotly_4.9.3      bookdown_0.21    
[31] rmarkdown_2.6     startup_0.15.0    ggplot2_3.3.3    
[34] purrr_0.3.4       tidyr_1.1.2       magrittr_2.0.1   
[37] scales_1.1.1      ellipsis_0.3.1    htmltools_0.5.0  
[40] assertthat_0.2.1  colorspace_2.0-0  lazyeval_0.2.2   
[43] munsell_0.5.0     crayon_1.3.4 
``````
