### ISSUE TITLE
control table and figure seq_id from yaml header or chunk options

### ISSUE THREAD

**Issue by zilch42** [davidgohel/officedown#71]
The issue I am experiencing is that officedown uses different field code SEQ ids for tables and figures than word so if I create a word document with officedown and then make a few table or figure additions manually, they end up belonging to different sequences. This may be a locale thing, I'm not sure. I am using an Australian version of Word. 

manually generated in word:
{ SEQ Table \* ARABIC }
{ SEQ Figure \* ARABIC }

generated by officedown
{SEQ tab \* Arabic}
{SEQ fig \* Arabic}

I understand the officer has some control over this with run_autonum(seq_id = "fig") but I don't call that directly when using officedown: e.g:

\```{r tab.cap='iris', tab.id='iris'}
head(iris)
\```

Would it be possible to have options either in the yaml header or chunk options (so that global defaults could be set) for defining which seq_id is used? If this is a locale based issue then it would allow users to define the correct ID for their localized version of word.

E.g.

```
officedown::rdocx_document:
  base_format: "bookdown::word_document2"
  reference_docx: "template.docx"
  number_sections: FALSE
  tables:
    style: Table_CSIRO
    caption: 
      style: Caption
      pre: 'Table '
      sep: ' '
      seq_id: Table
    conditional:
      first_row: true
      first_column: true
      last_row: false
      last_column: false
      no_hband: false
      no_vband: true
  plots:
    style: 'Body Text'
    caption: 
      style: Caption
      pre: 'Figure '
      sep: ' '
      seq_id: Figure
```

If there is already a way of doing this, please forgive me. I have looked everywhere for it.
