### ISSUE TITLE
Figure/Table caption pre bold

### ISSUE THREAD

**Issue by xiaochi-liu** [davidgohel/officedown#76]
Hello, may I ask how to set the captions of figure and table like the following appearance:

**Figure 1**. This is a plot.
**Table 1**. This is a table.

That is, is it possible to make the pre Figure/Table bold when setting the parameters:

```
tables:
  caption:
    style: Table Caption
    pre: 'Table '
    sep: '. '
plots:
  caption:
    style: Image Caption
    pre: 'Figure '
    sep: '. '
```
I think this is the style that most journal/thesis requires.

Your kind guidance is much appreciated!

**Comment by davidgohel** [comment]
Hello,

In the latest version, an option has been made available for that, you can use a knitr option or define that option in the header.

knitr chunk option: `cap.fp_text`, it expects an object returned by `officer::fp_text_lite()`

Or in the YAML header:

```
...
tables:
  caption:
    fp_text: !expr officer::fp_text_lite(bold = TRUE)
```
